ADB commands:

| **Category**          | **Command**                                                  | **Description**                                                                                                                                                                         |
|-----------------------|--------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **ADB Server**        | `adb kill-server`                                            | Kill the ADB server.                                                                                                                                                                    |
|                       | `adb start-server`                                           | Start the ADB server.                                                                                                                                                                   |
| **ADB Reboot**        | `adb reboot`                                                 | Reboot the device.                                                                                                                                                                      |
|                       | `adb reboot recovery`                                        | Reboot into recovery mode.                                                                                                                                                               |
|                       | `adb reboot-bootloader`                                      | Reboot into bootloader/fastboot mode.                                                                                                                                                   |
|                       | `adb root`                                                   | Restart ADB with root permissions.                                                                                                                                                       |
| **Shell**             | `adb shell`                                                  | Open or run commands in a terminal on the host Android device.                                                                                                                          |
| **Devices**           | `adb usb`                                                    | Restart ADB with USB debugging enabled.                                                                                                                                                 |
|                       | `adb devices`                                               | List connected devices.                                                                                                                                                                 |
|                       | `adb devices -l`                                            | List devices with detailed info (product/model).                                                                                                                                        |
|                       | `adb connect ip_address_of_device`                          | Connect to a device over the network.                                                                                                                                                   |
| **Get Android Version**| `adb shell getprop ro.build.version.release`              | Get the Android version.                                                                                                                                                                |
| **LogCat**            | `adb logcat`                                                 | View the device's system log.                                                                                                                                                           |
|                       | `adb logcat -c`                                              | Clear the current logs on the device.                                                                                                                                                   |
|                       | `adb logcat -d > [path_to_file]`                            | Save logcat output to a file.                                                                                                                                                           |
|                       | `adb bugreport > [path_to_file]`                            | Dump device information, including logcat, to a file.                                                                                                                                   |
| **Files**             | `adb push [source] [destination]`                            | Copy files from your computer to your phone.                                                                                                                                            |
|                       | `adb pull [device_file] [local_file]`                        | Copy files from your phone to your computer.                                                                                                                                            |
| **App Install**       | `adb -e install path/to/app.apk`                            | Install an APK file on an emulator.                                                                                                                                                     |
|                       | `adb -d install path/to/app.apk`                            | Install an APK file on a connected device.                                                                                                                                              |
|                       | `adb install -r path/to/app.apk`                            | Install an APK and replace if it exists.                                                                                                                                               |
|                       | `adb install -k path/to/app.apk`                            | Install an APK and keep its data.                                                                                                                                                       |
| **App Uninstall**     | `adb uninstall com.myAppPackage`                            | Uninstall an app by package name.                                                                                                                                                        |
|                       | `adb uninstall -k com.myAppPackage`                         | Uninstall an app without deleting data.                                                                                                                                                 |
|                       | `adb shell pm uninstall com.example.MyApp`                  | Uninstall using shell.                                                                                                                                                                  |
|                       | `adb shell pm clear [package]`                              | Clear all data associated with an app.                                                                                                                                                  |
|                       | `adb devices | tail -n +2 | cut -sf 1 | xargs -IX adb -s X uninstall com.myAppPackage` | Uninstall from all connected devices.                                                                                                                                                  |
| **App Update**        | `adb install -r yourApp.apk`                                | Reinstall an APK and keep its data.                                                                                                                                                     |
|                       | `adb install -k <.apk file path>`                           | Install an APK and keep its data.                                                                                                                                                       |
| **Home Button**       | `adb shell am start -W -c android.intent.category.HOME -a android.intent.action.MAIN` | Simulate pressing the Home button.                                                                                                                                                    |
| **Activity Manager**  | `adb shell am start -a android.intent.action.VIEW`         | Start an activity with a VIEW action.                                                                                                                                                   |
|                       | `adb shell am broadcast -a 'my_action'`                     | Broadcast an intent with a custom action.                                                                                                                                              |
|                       | `adb shell am start -a android.intent.action.CALL -d tel:+972527300294` | Make a call.                                                                                                                                                                       |
|                       | `adb shell am start -a android.intent.action.SENDTO -d sms:+972527300294 --es sms_body "Test" --ez exit_on_sent false` | Open SMS screen.                                                                                                |
|                       | `adb shell pm reset-permissions -p your.app.package`       | Reset app permissions.                                                                                                                                                                  |
|                       | `adb shell pm grant [packageName] [Permission]`            | Grant a permission to an app.                                                                                                                                                           |
|                       | `adb shell pm revoke [packageName] [Permission]`           | Revoke a permission from an app.                                                                                                                                                        |
| **Screen & Display** | `adb shell wm size 2048x1536`                               | Set screen resolution.                                                                                                                                                                   |
|                       | `adb shell wm density 288`                                   | Set screen density.                                                                                                                                                                     |
|                       | `adb shell wm size reset`                                    | Reset screen resolution.                                                                                                                                                                 |
|                       | `adb shell wm density reset`                                 | Reset screen density.                                                                                                                                                                   |
| **Input Text**        | `adb shell input text 'Wow, it's so cool feature'`           | Input text on the device.                                                                                                                                                                |
| **Screenshot**        | `adb shell screencap -p /sdcard/screenshot.png`             | Capture a screenshot.                                                                                                                                                                   |
| **Screen Recording**  | `adb shell screenrecord /sdcard/NotAbleToLogin.mp4`         | Record the screen.                                                                                                                                                                      |
|                       | `adb shell screenrecord --verbose /sdcard/demo.mp4`         | Record with verbosity.                                                                                                                                                                  |
| **Key Events**        | `adb shell input keyevent 3`                                | Send key event (e.g., Home button).                                                                                                                                                     |
|                       | `adb shell input keyevent 4`                                | Back button.                                                                                                                                                                            |
|                       | `adb shell input keyevent 5`                                | Call button.                                                                                                                                                                            |
|                       | `adb shell input keyevent 6`                                | End call button.                                                                                                                                                                        |
|                       | `adb shell input keyevent 26`                               | Power button (toggle device on/off).                                                                                                                                                   |
|                       | `adb shell input keyevent 27`                               | Camera button.                                                                                                                                                                          |
|                       | `adb shell input keyevent 64`                               | Open browser.                                                                                                                                                                           |
|

                       | `adb shell input keyevent 66`                               | Enter key.                                                                                                                                                                              |
|                       | `adb shell input keyevent 67`                               | Delete (backspace) key.                                                                                                                                                                 |
|                       | `adb shell input keyevent 207`                              | Contacts key.                                                                                                                                                                           |
|                       | `adb shell input keyevent 220 / 221`                        | Brightness down/up keys.                                                                                                                                                                |
|                       | `adb shell input keyevent 277 / 278 / 279`                  | Cut/Copy/Paste keys.                                                                                                                                                                    |
| **Shared Preferences**| `adb shell 'am broadcast -a org.example.app.sp.PUT --es key key_name --es value "hello world!"'` | Add a value to default shared preferences.                                                             |
|                       | `adb shell 'am broadcast -a org.example.app.sp.REMOVE --es key key_name'`                             | Remove a value from default shared preferences.                                                                                                                                       |
|                       | `adb shell 'am broadcast -a org.example.app.sp.CLEAR --es key key_name'`                               | Clear all default shared preferences.                                                                                                                                                |
|                       | `adb shell 'am broadcast -a org.example.app.sp.PUT --es name Game --es key level --ei value 10'`     | Specify shared preferences file and data types.                                                                                                                                      |
| **Monkey**            | `adb shell monkey -p com.myAppPackage -v 10000 -s 100`       | Use Monkey tool to generate random events on a device.                                                                                                                                  |
| **Paths**             | `/data/data/<package>/databases`                             | App databases path.                                                                                                                                                                      |
|                       | `/data/data/<package>/shared_prefs/`                         | Shared preferences path.                                                                                                                                                                 |
|                       | `/data/app`                                                   | APKs installed by the user.                                                                                                                                                              |
|                       | `/system/app`                                                 | Pre-installed APK files.                                                                                                                                                                 |
|                       | `/mnt/asec`                                                   | Encrypted apps (App2SD).                                                                                                                                                                 |
|                       | `/mnt/emmc`                                                   | Internal SD Card.                                                                                                                                                                        |
|                       | `/mnt/sdcard`                                                 | External/Internal SD Card.                                                                                                                                                                |
|                       | `/mnt/sdcard/external_sd`                                     | External SD Card.                                                                                                                                                                        |
| **Device Information**| `adb shell ls`                                                | List directory contents.                                                                                                                                                                 |
|                       | `adb shell ls -s`                                            | Print file sizes.                                                                                                                                                                        |
|                       | `adb shell ls -R`                                            | List subdirectories recursively.                                                                                                                                                          |
| **Device Info**       | `adb get-state`                                              | Print device state.                                                                                                                                                                      |
|                       | `adb get-serialno`                                           | Get the serial number.                                                                                                                                                                   |
|                       | `adb shell dumpsys iphonesybinfo`                            | Get the IMEI.                                                                                                                                                                            |
|                       | `adb shell netstat`                                          | List TCP connectivity.                                                                                                                                                                   |
|                       | `adb shell pwd`                                              | Print current working directory.                                                                                                                                                         |
|                       | `adb shell dumpsys battery`                                  | Battery status.                                                                                                                                                                          |
|                       | `adb shell pm list features`                                 | List phone features.                                                                                                                                                                     |
|                       | `adb shell service list`                                     | List all services.                                                                                                                                                                       |
|                       | `adb shell dumpsys activity <package>/<activity>`             | Activity info.                                                                                                                                                                           |
|                       | `adb shell ps`                                               | Print process status.                                                                                                                                                                    |
|                       | `adb shell wm size`                                          | Display current screen resolution.                                                                                                                                                        |
|                       | `adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp'` | Current app's opened activity.                                                                                    |
| **Package Info**      | `adb shell list packages`                                    | List package names.                                                                                                                                                                      |
|                       | `adb shell list packages -r`                                 | List package names with paths to APKs.                                                                                                                                                   |
|                       | `adb shell list packages -3`                                 | List third-party package names.                                                                                                                                                          |
|                       | `adb shell list packages -s`                                 | List only system packages.                                                                                                                                                               |
|                       | `adb shell list packages -u`                                 | List package names of uninstalled apps.                                                                                                                                                  |
|                       | `adb shell dumpsys package packages`                         | List info on all apps.                                                                                                                                                                   |
|                       | `adb shell dump <name>`                                      | List info on one package.                                                                                                                                                                |
|                       | `adb shell path <package>`                                   | Path to the APK file.                                                                                                                                                                    |
| **Configure Settings**| `adb shell dumpsys battery set level <n>`                    | Change battery level (0 to 100).                                                                                                                                                         |
|                       | `adb shell dumpsys battery set status <n>`                   | Change battery status (unknown, charging, discharging, not charging, full).                                                                                                             |
|                       | `adb shell dumpsys battery reset`                            | Reset battery status.                                                                                                                                                                    |
|                       | `adb shell dumpsys battery set usb <n>`                      | Change USB connection status (ON or OFF).                                                                                                                                               |
|                       | `adb shell wm size WxH`                                      | Set screen resolution.                                                                                                                                                                   |
|                       | `adb backup -apk -all -f backup.ab`                          | Backup settings and apps.                                                                                                                                                                |
|                       | `adb backup -apk -shared -all -f backup.ab`                  | Backup settings, apps, and shared storage.                                                                                                                                              |
|                       | `adb backup -apk -nosystem -all -f backup.ab`                | Backup only non-system apps.                                                                                                                                                             |
|                       | `adb restore backup.ab`                                      | Restore from a backup.                                                                                                                                                                   |
| **Logs**              | `adb logcat [options] [filter] [filter]`                      | View device logs.                                                                                                                                                                        |
|                       | `adb bugreport`                                              | Print bug reports.                                                                                                                                                                       |
| **Other**             | `adb backup`                                                 | Create a full backup of your phone and save it to the computer.                                                                                                                          |
|                       | `adb restore`                                                | Restore a backup to your phone.                                                                                                                                                          |
|                       | `adb sideload`                                               | Push and flash custom ROMs and zips from your computer.                                                                                                                                 |

These commands cover various aspects of working with Android devices using ADB.
